# Docker Compose configuration for 53one

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 53one-app
    restart: unless-stopped
    ports:
      - "3000:5173"
    env_file: ".env"
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
      - AUTH_TRUST_HOST=true
      - MONGODB_URI=mongodb://mongodb:27017/53one?ssl=false
      - NEXTAUTH_URL=http://localhost:5731
      - ORIGIN=http://localhost:5731
    depends_on:
      - mongodb
    networks:
      - 53one-network

  mongodb:
    image: mongo:6
    container_name: 53one-mongodb
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - 53one-network

networks:
  53one-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
