name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          # Need to use a GH App if you want CI to run on release PRs
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: 'simple'