name: release-please

on:
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: jburns24/53one
          identity: release-please
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          # Using octo-sts to get a temporarty token. Needed so this workflow
          # will trigger other workflows (ie: the tag pushed by this workflow will trigger release.yaml)
          token: ${{ steps.octo-sts.outputs.token }}
          release-type: 'simple'